### ISSUE TITLE
uninstall plugin

### ISSUE THREAD

**Issue by benrichit** [felixrindt/pretix-telephone#13]
how can i remove the plugin?
when updating to pretix 3.4.0 I always get an error "no module named" and then something with phonenumber. i suspect that this is related to the plugin?

**Comment by raphaelm** [comment]
No, this is probably related to a new dependency in pretix, not to this plugin. Please open an issue with the full error message in the main pretix repository.

**Comment by felixrindt** [comment]
Depending on how you installed the plugin, you can remove it in a similar way. (e.g. `pip uninstall pretix-telephone`)

To fix your error, you may just need to upgrade the dependencies from the requirements file, as pretix 3.4.0 [introduced](https://github.com/pretix/pretix/blob/8d1f9bf0f39d21e6c4960990c5100cbde9f478d0/src/requirements/production.txt#L63) new dependencies related to phone numbers.

As this looks like to not be related to this plugin, I'm closing this issue.
