### ISSUE TITLE
Release this on PyPI

### ISSUE THREAD

**Issue by raphaelm** [felixrindt/pretix-telephone#4]
Since this plugin might be useful to others, it'd be great to see it version-tagged and uploaded as a package on PyPI! Since you already have a setup.py file, it should be [quite easy to do](https://packaging.python.org/tutorials/distributing-packages/#upload-your-distributions).

(We've deploy this plugin to pretix Hosted recently, where it doesn't matter since we install everything from git repositories anyways, but for other users it would be easier this way.)

**Comment by felixrindt** [comment]
I started looking into that a while ago, but I'm really new to this. Hope I can ask you if I'm having questions :laughing:

**Comment by raphaelm** [comment]
Sure! :) Basically, you just need to set up your account there, set up your credentials locally, and then
```
python setup.py clean sdist bdist_wheel
twine upload
```

**Comment by felixrindt** [comment]
https://pypi.org/project/pretix-telephone/ ¯\_(ツ)_/¯

I got an `invalid command 'bdist_wheel'` error, so I just uploaded the source distribution. Also the package page isn't looking nice yet.

**Comment by raphaelm** [comment]
> pypi.org/project/pretix-telephone ¯_(ツ)_/¯

Nice!

> I got an invalid command 'bdist_wheel' error, so I just uploaded the source distribution. 

``pip install wheel`` fixes that :)

> Also the package page isn't looking nice yet.

Yeah, it wants a reStructuredText file, not Markdown :roll_eyes:

**Comment by felixrindt** [comment]
> pip install wheel fixes that :)

:roll_eyes: 

> Yeah, it wants a reStructuredText file, not Markdown roll_eyes

But isn't the [readme](https://github.com/felixrindt/pretix-telephone/blob/master/README.rst)  reStructuredText? Where is the error? I just modified the first paragraph after using the cookie cutter template.

**Comment by raphaelm** [comment]
You're correct. I don't know the answer right now :D

**Comment by felixrindt** [comment]
https://pypi.org/project/pretix-telephone/ looks completely fine now \o/
