### ISSUE TITLE
Feature request: Export of a list with names and phone numbers

### ISSUE THREAD

**Issue by raphaelm** [felixrindt/pretix-telephone#5]
Would be great to be able to get the data out, e.g. to call all numbers to notify that an event has been canceled.

**Comment by felixrindt** [comment]
I would expect this to work just like the email export.

**Comment by raphaelm** [comment]
Hmm, that would be one option, although when calling, it's probably best to have names in the export as well, so maybe more like the order list CSV.

**Comment by felixrindt** [comment]
A CSV seems more useful, although a little redundant, as there already is an order list exporter :/ 
Should include Order code and Invoice name imo.
